import uniqueRandomArray from "unique-random-array";
const questions = uniqueRandomArray([
  "What is $$ Spirit Animal?",
  "what do you think about $$",
  "who would be the person $$ die for",
  "where do you find $$ in another 10 years",
  "Who is there in $$ ’s emergency contact",
  "What is the first thing as a baby $$ had?",
  "What is $$'s guilty pleasure?",
  "Who is the last person that $$ stalked on social media?",
  "Why did $$'s last relationship end?",
  "What habit can’t $$ seem to quit?",
  "What is $$'s secret talent if they have one?",
  "What would $$ do with a million dollars?",
  "What is the most romantic thing that $$ has ever done?",
  "What is $$'s worst childhood memory?",
  "What would you name your boat if you had one?",
  "What’s the closest thing to real magic?",
  "Who is the messiest person you know?",
  "What will finally break the internet?",
  "What’s the most useless talent you have?",
  "What would be on the gag reel of your life?",
  "Where is the worst smelling place you’ve been?",
  "What celebrity would you rate as a perfect 10?",
  "What’s a body part that you wouldn’t mind losing?",
  "What is the dumbest way you’ve been injured?",
  "Which fictional character would be the most boring to meet in real life?",
  "What is the best and worst purchases you’ve ever made?",
  "If you had to change your name, what would your new name be, and why would you choose that name?",
  "What are some things that sound like compliments but are actually insults?",
  "What’s your biggest screw up in the kitchen?",
  "What’s the worst commercial you’ve recently seen?",
  "What is the craziest thing one of your teachers has done?",
  "When did you screw everything up, but no one ever found out it was you?",
  "What problem or situation did TV / movies make you think would be common, but when you grew up you found out it wasn’t?",
  "What quote or saying do people spout but is complete BS?",
  "What’s something your brain tries to make you do and you have to will yourself not to do it?",
  "If you could know the absolute and total truth to one question, what question would you ask?",
  "What’s the most interesting thing you’ve read or seen this week?",
  "What ridiculous thing has someone tricked you into doing or believing?",
  "If you were given a one-minute ad slot during the Super Bowl that you couldn’t sell, what would you fill it with?",



  "When was the last time $$ told a lie","What is $$ biggest fear","What is $$ guilty pleasure",
  "Who do $$ have a crush on",
  "If $$ had to date someone in this room, who would it be",
  "What is the meanest thing that $$ have done",
  "Who is the last person that $$ stalked on social media",
  "What is the craziest event that $$ have ever been to",
  "What is the worst dream that $$ have had",
  "Why did $$ last relationship end",
  "What is the most embarrassing thing that has happened to $$ this year",
  "What habit can’t $$ seem to quit",
  "Who is $$ celebrity crush",
  "What is a secret that $$ have never told anyone before",
  "How many people have $$ been with",
  "Would $$ stop talking to all of his friends for a million dollars",
  "Who was $$ first crush",
  "What is the most embarrassing music that $$ like to listen to",
  "If $$ and one person in this room could be the last people on Earth left alive, who would that person be",
  "Would $$ ever donate an organ to someone in this room",
  "Who in this room do $$ think would be the worst date",
  "Who in this room do $$ think would be the best date",
  "What is the worst intimate experience that $$ have had",
  "What is the worst thing about being $$ gender",
  "What is the most trouble that $$ ever got into in school",
  "When was a time that someone really betrayed $$ trust",
  "Do $$ sing in the shower",
  "When is the last time $$ threw up",
  "When is the last time $$ cried",
  "What is the most embarrassing thing that $$ have ever done in front of a crush",
  "What do $$ look for in a potential love interest",
  "What would $$ do with a million dollars",
  "Could $$ survive without any phone or internet for a month",
  "What is the most that $$ have ever had to drink",
  "What is the longest amount of time that $$ have ever been awake",
  "What is $$ biggest pet peeve",
  "When was the worst time that $$ threw up",
  "If $$ could only save one person in this room from a fire, who would it be",
  "Which person in the room do $$ think gossips the most",
  "What is $$ biggest insecurity",
  "What is the most expensive thing $$ bought that wasn’t a house or a car",
  "What is a common misconception about $$",
  "Where is the weirdest place that $$ have gone to the bathroom",
  "When was the most embarrassing time that $$ passed gas",
  "What was the most disgusting thing to ever come out of $$ body",
  "If $$ could live anywhere in the world, where would it be",
  "What do you think is $$ best physical quality",


]);

export const questionGenerator = names => {
  const name = uniqueRandomArray(names);
  const question = questions();
  return question.replace("$$", name());
};
